### ISSUE TITLE
Vgdisplay spec does not match sos report or rule

### ISSUE THREAD

**Issue by jhjaggars** [RedHatInsights/insights-core#13]
_From @bfahr on May 22, 2017 23:9_

The current `VgDisplay` mapper correctly parses the output for the `vgdisplay` command.  However the sos report uses `vgdisplay -vv` which will include additional information on logical and physical volumes.  The current mapper appears to have issues parsing the sos report data.

Also the `cmirror_perf_issue` rule utilizes a local mapper for `vgdisplay` which does parse this information, however since the spec does not use the `-vv` switch, no logical volume information is provided in the insights archive so the rule won't ever trigger in insights, but should work on sos reports.

The spec may need to be changed to add the `-vv` or `-v` switch if this information is not available via other specs.  The shared mapper `VgDisplay` needs to be updated so that it will work with sos reports and the spec if updated.  The rule needs to be revised to replace the local `vgdisplay` mapper with the shared mapper.

_Copied from original issue: RedHatInsights/falafel#232_

**Comment by miclark** [comment]
Hey @PaulWay,  assigning this to you.  Trying to prioritize bugs over other tasks.  If you don't feel it's appropriate to work this one, let me know and we'll move it around.

**Comment by PaulWay** [comment]
Hi @miclark - sure thing, will do!

**Comment by PaulWay** [comment]
OK, I've had to mostly rewrite the parsing of VgDisplay, but all the previous tests pass, it reads the complete set of information from the ``-vv`` output, and it provides ``debug_info`` and ``vg_list`` properties to access the data directly.

There's a minor incompatibility with the ``lvm_filter.py`` rule plugin, which I think is because the plugin does not attempt to order the error lines it gets from VgDisplay and because we no longer force this to be a set the order has changed.  I feel the lvm_filter plugin should be changed to be more consistent in the face of varying output, but I'm open to better suggestions.

I haven't completed the documentation on this module, so I'll get to this next week when I'm back from PTO.

**Comment by PaulWay** [comment]
OK, I've submitted #272 for this.  The spec now tries to request `vgchange -vv` first, and then falls back to `vgchange`, so it should be compatible with old archives as well as sosreports.  I'm now updating the `cmirror_perf_issue` rule to use these as well as use the `@condition` syntax for better statistics reporting.

**Comment by PaulWay** [comment]
This is merged now so I think we're good to go.
