### ISSUE TITLE
Mistake to recognize collected files as missing requirements

### ISSUE THREAD

**Issue by wushiqinlou** [RedHatInsights/insights-core#1466]
When I tried to reformat the output of missing requirements from "-m" option in insights-run, I found that insights-run would recognize collected soft link files from sosreport as missing. For example, when I executed insights-run with a sosreport collected from my local server, the command reported following item in the missing_requirements section:

~~~
<class 'insights.parsers.lsmod.LsMod'>:[[insights.specs.Specs.lsmod],[]]
~~~

That means insights-run thought there was no lsmod file in the sosreport. However, I am pretty sure that the lsmod file exists in the directory. 

~~~
# ls
boot           dmidecode      installed-rpms lib            mount          root           sos_reports    usr
chkconfig      etc            ip_addr        lsmod          netstat        route          sys            var
date           free           java           lsof           proc           sos_commands   uname          version.txt
df             hostname       last           lspci          ps             sos_logs       uptime         vgdisplay
~~~

The item of lsmod in sos_archive.py is "lsmod = simple_file("lsmod")", after changing the item as "lsmod = simple_file("sos_commands/kernel/lsmod")" and execute insights-run again, lsmod missing disappears in the missing_requirements section. So I think there may be issue in handling soft link files in sosreport.

**Comment by csams** [comment]
Hey @wushiqinlou, thanks for bringing this up! It should happen only when analyzing a sos report that's already been extracted to a directory. It's caused by [code that checks to ensure symlinks don't point outside the archive](https://github.com/RedHatInsights/insights-core/blob/master/insights/core/spec_factory.py#L144).

I'll push a fix shortly, but until then, analyzing the archive without extracting it should work as expected.
