### ISSUE TITLE
httpd_V combiner doesn't treat httpd_V parser arg as a list

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#1805]
The [httpd_V combiner](https://github.com/RedHatInsights/insights-core/blob/master/insights/combiners/httpd_V.py#L79) treats the HttpdV parser parameter as a single instance when it is a list ([the httpd_V spec is multi_output](https://github.com/RedHatInsights/insights-core/blob/master/insights/specs/__init__.py#L188)). The combiner always fails if the parser is available.

**Comment by xiangce** [comment]
@csams - Thanks for pointing that out. However, in fact, the [httpd_V combiner](https://github.com/RedHatInsights/insights-core/blob/master/insights/combiners/httpd_V.py#L57) was deprecated after the [httpd_V spec](https://github.com/RedHatInsights/insights-core/blob/master/insights/specs/default.py#L341) being changed to use `foreach_execute` in #1018. 

It's possible, multiple `httpd` instances based on different httpd version can be set up and running on one host. So, the combiner is no longer necessary. And instead of the combiner, the `foreach_execute` spec allows collecting all the running instances and parsing them one by one.

Is it necessary to update the deprecated combiner?

**Comment by xiangce** [comment]
@csams - A bit supplement: The current (new) spec which is trying to collect the HttpdV info of all the running `httpd` processes conflicts with the [httpd_V combiner](https://github.com/RedHatInsights/insights-core/blob/master/insights/combiners/httpd_V.py#L57). 

The new spec tries to collect all the running `httpd` processes. But the httpd_V combiner only reserve one of them. This is not so correct.

Maybe we'd better remove the incorrect httpd_V combiner, how do you think?

**Comment by miclark** [comment]
I don't see any use of this combiner.  And it has been deprecated for over a year.  Given it is broken, I would opt to just remove it.   @csams does that sound good to you?  How did you come across the bug?

**Comment by xiangce** [comment]
@csams, how do you think about removing this deprecated httpd_V combiner? If OK, I'll remove it. Or I'll just close this comment and leave it as deprecated.

**Comment by csams** [comment]
Sorry for the delay here folks. My github notifications are a mess. I came across it in the error reports. Just removing it is fine with me if it's not used anywhere.
