### ISSUE TITLE
Update is_hypervisor check in InstalledRpms

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#1928]
The [is_hypervisor check](https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/installed_rpms.py#L229) in `InstalledRpms` targets only rhel6 and rhel7. Does it need updating for rhel8? Also, it seems like this should this be folded into / removed in favor of the [VirtWhat](https://github.com/RedHatInsights/insights-core/blob/master/insights/combiners/virt_what.py) combiner.

**Comment by koalakangaroo** [comment]
@psachin - please check this.

**Comment by psachin** [comment]
@csams Sadly we can't verify this at the moment because RHEL-8 host support for RHV is only available on RHV-4.4(No GA release date for RHV-4.4 GA is announced). However after the GA, we have to update `is_hypervisor_check` by adding `.el8ev` check(or something similar), but I'm in favor of deprecating `is_hypervisor_check` because:

1. The method is only useful for RHEV rules whereas `VirtWhat` combiner has more generic usage across other platforms including OpenStack.
2. The method is only used by [one rule](https://github.com/RedHatInsights/insights-plugins/blob/master/telemetry/rules/plugins/rhev/rhev_lro_on.py)
3. and we have existing RHEV rules using enhanced [method](https://github.com/RedHatInsights/insights-plugins/blob/master/telemetry/rules/plugins/rhev/__init__.py#L6) to check the hypervisor or `vdsm` package.

**Comment by xiangce** [comment]
@JoySnow - Please have a look

**Comment by JoySnow** [comment]
@psachin  I agree with the deprecation of the usage of `is_hypervisor` in our plugin repo.

**Comment by psachin** [comment]
@csams The plugins are updated to use internal function to check the `vdsm` package. The property function `is_hypervisor` can be deprecated/remove.
