### ISSUE TITLE
Please add parser:OVSvsctlListBridge for sosreport

### ISSUE THREAD

**Issue by zerodayz** [RedHatInsights/insights-core#1976]
Please add parser:OVSvsctlListBridge for sosreport

https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/ovs_vsctl_list_bridge.py

**Comment by miclark** [comment]
This appears to require the addition of a new sosreport spec.  @zerodayz, do you have the location of the file in a sosreport?

**Comment by zerodayz** [comment]
@miclark We have got `/sosreport/sos_commands/openvswitch/ovs-vsctl_list_bridge_br-int` and others such as `/sosreport/sos_commands/openvswitch/ovs-vsctl_list_bridge_br-ex` These files combined are making `ovs-vsctl list bridge` output

**Comment by xiangce** [comment]
For insights-archive, there is a spec to collect the output of the command `ovs-vsctl list bridge` which will output the information about all `bridges`. But in sosreport-archive, this command has been separated into individual files for each `bridge`.


To support both the separated files in sosreport and single file in insights-archive, the following steps are required:

1. Add a new parser OVSvsctlListBridgeSos to just parse the separated files in sosreport, which stored parsed result in a list.
   - Since there are existing rules used the `OVSvsctlListBridge`, better do not apply it to the sos-archive separated file directly.
2. Add a combiner to combine the parsed result of both `OVSvsctlListBridge` and `OVSvsctlListBridgeSos`

**Comment by xiangce** [comment]
I'll take this issue

**Comment by zerodayz** [comment]
@xiangce  We might not need to do it, if the sosreport PR will be merged. Requested adding `ovs-vsctl list bridge` to the sosreport archive

**Comment by xiangce** [comment]
@zerodayz - cool, that's great. Then, I will fix this issue until  https://github.com/sosreport/sos/pull/1698 being merged

**Comment by miclark** [comment]
Having sosreport/sos#1698 merged will not solve the problem since users are not required to update sosreport.  I think the combiner still makes sense.

**Comment by xiangce** [comment]
Ack, makes sense to me. Will do the corresponding updates
