### ISSUE TITLE
ModuleNotFoundError: No module named 'insights.config'

### ISSUE THREAD

**Issue by chenlizhong** [RedHatInsights/insights-core#2009]
In /insights-core/insights/archive/tool.py, below import is broken.

from insights.config import CommandSpec
from insights.config.static import get_config

**Comment by xiangce** [comment]
This ERROR occurs when passing 'telemetry' to the `-p` instead of `telemetry/rules`

~~~
❱ insights run -p telemetry /tmp/insights-rhel7-box-20190401110721
ERROR:insights.core.dr:No module named 'insights.config'
Traceback (most recent call last):
  File "/Users/liuxc/work/insights/insights-core/insights/core/dr.py", line 378, in _import
    return importlib.import_module(path)
  File "/Users/liuxc/work/insights/insights-core/insights/contrib/importlib.py", line 37, in import_module
    __import__(name)
  File "/Users/liuxc/work/insights/insights-plugins/telemetry/demo/__init__.py", line 6, in <module>
    from insights.archive.tool import TestArchive, Transform as T
  File "/Users/liuxc/work/insights/insights-core/insights/archive/tool.py", line 12, in <module>
    from insights.config import CommandSpec
ModuleNotFoundError: No module named 'insights.config'
~~~

I'll look in to it.

**Comment by xiangce** [comment]
The `telemetry.demo` tries to import modules from `insights.archive.tool` and there are broken `import`s as below:
https://github.com/RedHatInsights/insights-core/blob/2db4d39db820237ec602666f7c0e5eeb3930da32/insights/archive/tool.py#L12-L13
* there is no such `insights.config` modules at all.

The `insights.config` has been removed and substituted by the `insights.specs` for a long time.

I have no idea about the usage of `insights.archive.tool` and `telemetry.demo`, except for the `telemetry.demo`, there is no other modules use `insights.archive.tool`. 

@kylape, would you please to help to confirm if we could remove them (`insights.archive.tool` and `telemetry.demo`)?

**Comment by csams** [comment]
Hey @xiangce , we're planning to remove the archive package in core since it's leftover from 1.x. The demo stuff in telemetry is also leftover from 1.x and should be removed, too. I don't think anything could have been using it for a long time in its current state.

**Comment by csams** [comment]
The archive creation code is being removed with https://github.com/RedHatInsights/insights-core/pull/2020

**Comment by xiangce** [comment]
@csams @lhuett, Thanks for the confirmation and action.
