### ISSUE TITLE
Add regex support to add_filter

### ISSUE THREAD

**Issue by sourabhtk37** [RedHatInsights/insights-core#2029]
It would be great [add_filter](https://github.com/RedHatInsights/insights-core/blob/master/insights/core/filters.py#L49) supports pattern matching with regex also.

**Comment by csams** [comment]
@sourabhtk37 Thanks for the suggestion! We considered this a while ago and decided not to support it for a couple of reasons. The first is that the insights clients in the wild don't support regex filtering. The second is because regexes can be expensive to execute depending on complexity and input length. If we can ever get to where core itself is handling collection, we can do more complicated filtering client side that will remove the need for this kind of filtering in many cases. If you're working on something other than insights archives, please email me.
