### ISSUE TITLE
Modinfo Parser is Missing Insights Archive Spec

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#2053]
An insights archive spec needs to be added for the new data source for #2039.

**Comment by xiangce** [comment]
Hey @bfahr, Can the `foreach_execute` specs be collected by the clients? I thought it still cannot be collected, so I didn't ask @jsvob to add it into the uploader.json and `insights_archive.py` file as well in the PR#2039.

And, due to this reason (no files in the archive), the new "ModinfoEach" parser will not work before client-V3. To make some existing rules work, several necessary Parsers/Specs have been added as a workaround: modinfo_i40e(`ModInfoI40e`), modinfo_vmxnet3(`ModInfoVmxnet3`), modinfo_igb (`ModInfoIgb`), modinfo_ixgbe(`ModInfoIxgbe`), and modinfo_veth(`ModInfoVeth`). 

Once a new Spec is added to the `insights_archive.py` for `ModinfoEach`, it would look like `modinfo = glob_file("insights_commands/modinfo_*)`. This will cause the `ModinfoEach` parser to be applied to the above existing specs as well. Is it OK?

**Comment by miclark** [comment]
We need to add `modinfo = glob_file("insights_commands/modinfo_*")` to `insights_archive.py`, and I think we should be good.  @xiangce, I'll let you add that PR.

We can deprecate the five pre-existing parsers once we have the core-3 collection in place.
