### ISSUE TITLE
ProcMounts doesn't handle paths contain spaces, e.g."/run/media/VMware Tools"

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#2069]
At first, need to figure out how the path with spaces is represented in `/proc/mounts`?

then take corresponding enhancement for it.

**Comment by ppandey-redhat** [comment]
@xiangce 

In `/proc/mounts`,  spaces are encoded using `\040 (octal value)` similar to they are handled in `fstab`. Since the various options in /etc/fstab are separated by spaces, it is not possible to put spaces in the path of the mount point. This limitation is easily bypassed by typing "\ 040" instead of a space in the configuration file.
Ref: https://unix.stackexchange.com/questions/317476/shell-code-to-check-if-a-device-or-file-with-spaces-in-the-path-is-mounted

Example: `/dev/sda1 /mnt/first\040disk ext3 options 0 0`
