### ISSUE TITLE
MountEntry in mount.py store 2 copy of data in both obj.attribute and self.data ways, which may lead to data inconsistency once abuse write operations are applied to it. 

### ISSUE THREAD

**Issue by JoySnow** [RedHatInsights/insights-core#2081]
Even though such write operations won't be used in our normal usage of parsers, this is still a shortcoming in some way.

Here is a abuse writing example:

At file `test_mount.py`'s Line-60, I add following test code for example:
```
    import pprint
    print("\n === Take this as an example: ")
    print("sr0, type(sr0): ", sr0, type(sr0))
    print("sr0.__dict__ : ")
    pprint.pprint(sr0.__dict__)
    print("sr0.data['mount_point'], sr0.mount_point: ", sr0.data['mount_point'], sr0.mount_point)
    print(" === Do the change now: ")
    sr0.mount_point = "attribute mp"               # <-- change attribute here
    print("sr0.data['mount_point'], sr0.mount_point: ", sr0.data['mount_point'], sr0.mount_point)
    sr0.data['mount_point'] = "data dict mp"   # <-- change in data here
    print("sr0.data['mount_point'], sr0.mount_point: ", sr0.data['mount_point'], sr0.mount_point)
```
And here is the result in `py.test`:
```
insights/parsers/tests/test_mount.py::test_mount 
 === Take this as an example: 
sr0, type(sr0):  <insights.parsers.mount.MountEntry object at 0x7f9b6c2dda20> <class 'insights.parsers.mount.MountEntry'>
sr0.__dict__ : 
{'data': {'filesystem': '/dev/sr0',
          'mount_clause': '/dev/sr0 on /run/media/root/VMware Tools type '
                          'iso9660 '
                          '(ro,nosuid,nodev,relatime,uid=0,gid=0,iocharset=utf8,mode=0400,dmode=0500,uhelper=udisks2) '
                          '[VMware Tools]',
          'mount_label': 'VMware Tools',
          'mount_options': <insights.parsers.mount.MountOpts object at 0x7f9b6c3124e0>,
          'mount_point': '/run/media/root/VMware Tools',
          'mount_type': 'iso9660'},
 'filesystem': '/dev/sr0',
 'mount_clause': '/dev/sr0 on /run/media/root/VMware Tools type iso9660 '
                 '(ro,nosuid,nodev,relatime,uid=0,gid=0,iocharset=utf8,mode=0400,dmode=0500,uhelper=udisks2) '
                 '[VMware Tools]',
 'mount_label': 'VMware Tools',
 'mount_options': <insights.parsers.mount.MountOpts object at 0x7f9b6c3124e0>,
 'mount_point': '/run/media/root/VMware Tools',
 'mount_type': 'iso9660'}
sr0.data['mount_point'], sr0.mount_point:  /run/media/root/VMware Tools /run/media/root/VMware Tools
 === Do the change now:   
sr0.data['mount_point'], sr0.mount_point:  /run/media/root/VMware Tools attribute mp
sr0.data['mount_point'], sr0.mount_point:  data dict mp attribute mp
```

**Comment by JoySnow** [comment]
@xiangce  Feel free to comment ...

**Comment by csams** [comment]
Hey everybody,

For `MountEntry`, I think we should remove the `.data` attribute altogether and have standard attributes that get assigned in the `__init__` of the class. We should also include them in the pydoc of the class or init function.

If rules are already using the `.data` dictionary directly, there's not much we can do to protect it other than wrapping it in a property and returning a deep copy on every access. If we have to go that way, I'd prefer to also create a property for each attribute that delegates to the backing data dict and bypasses the copy. e.g.

```python
class MountEntry(object):
    def __init__(self, data=None):
        self._data = data if data is not None else {}

    @property 
    def data(self):
        return copy.deepcopy(self._data)

    @property 
    def mount_clause(self):
        return self._data.get("mount_clause", "")
...
```
That won't protect `self._data`, but.. this is python. :)

**Comment by xiangce** [comment]
@csams - I agree with you that we should remove the `.data` attribute. Since I have already removed the dependency on it from rules. I think it's OK to remove it.

I just wrote a `DictToAttribute`: 
https://github.com/RedHatInsights/insights-core/blob/099771e692e036fc5a99e291be64720d8e5db9e5/insights/core/__init__.py#L1624-L1656 as the base of the `MountEntry` and `MountOpts`, would you please to have a check and may I get your suggestions to it?

Thanks.

**Comment by csams** [comment]
Hey @xiangce , since we don't have to deal with `.data`, we should just create plain attributes in the `__init__` of `MountEntry` and `MountOpts` instead of having another class create them from `.attrs`:

```python
def __init__(self, data=None):
    data = {} if data is None else data
    self.foo = data.get("foo")
    self.bar = data.get("bar")
...
```

**Comment by xiangce** [comment]
@csams - Sure, we can do that. However, 

1. This isn't suitable to the `MountOpts`, since there are too many different `mount_options` to set all of them as attributes in advance. E.g.
  - (apfs, local, noexec, journaled, noatime, nobrowse)
  - (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
  - (rw,relatime,fd=40,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=19906)

2. And there are a lot of existing rules have accessed the `MountOpts` (and `MoundEntry`) in both the `attribute` and `dict[]/.get()` way, e.g.

To keep them work, I think we'd better remove the `.attributes` and revert the `self._data` back.

**Comment by xiangce** [comment]
Hey @csams, I raised a new #2104 to resolve this issue. Please kindly review.

**Comment by csams** [comment]
Hey @xiangce @JoySnow, @bfahr and I were looking at this again this morning, and I don't think there's a problem with the original implementation before the PRs. We duplicate some data, but I'm not worried about that for mount entries. Inconsistency shouldn't be a problem since nothing outside of a parser should modify it anyway, and if somebody wants to, we can't _really_ prevent it.

It's good to flag duplication and possible consistency problems, but I think we can safely ignore them in this case unless they're currently causing other issues.

**Comment by xiangce** [comment]
Hey @csams, I think since we already realized the duplication problem, we'd better resolve it.

I reverted the `MountOpts` back and removed the `self._data` in the #2104, please have a look whenever free.
