### ISSUE TITLE
Better keep the spec `modinfo` compatible with the one in sosreport

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-core#2220]
_Originally posted by @xiangce in https://github.com/RedHatInsights/insights-core/pull/2212#issuecomment-534346801_

> @crackcodecamp  - I found the following kind of files in the sosreport archives:
> 
> ~~~
> ❱ ls sosreport-DutyOSS.01950525-20171015064632/sos_commands/kernel/modinfo_*
> sosreport-DutyOSS.01950525-20171015064632/sos_commands/kernel/modinfo_tpm_tpm_tis_libata_efivars_tcp_cubic_kernel_printk_kgdb_spurious_pstore_dynamic_debug_pcie_aspm_pci_hotplug_pciehp_acpiphp_intel_idle_acpi_pci_slot_processor_thermal_acpi_memhotplug_battery_keyboard_vt_8250_kgdboc_kgdbts_scsi_mod_pcmcia_core_pcmci
> 
> ❱ ls sosreport-silverdc1-02344573-2019-03-25-qbgwlyf/sos_commands/kernel/modinfo_*
> sosreport-silverdc1-02344573-2019-03-25-qbgwlyf/sos_commands/kernel/modinfo_ALL_MODULES
> ~~~
> 
> But the current parser of ModinfoEach is for single module-info file, e.g. `modinfo pcmci`, it will get an incorrect parser result when applying to the merged file, e.g `modinfo_ALL_MODULES`.
> 
> I'll raise an issue for this problem, and merge this PR after that issue is fixed.
>

**Comment by xiangce** [comment]
Hey @jsvob and @bfahr ,

The current ModinfoEach works for the `modinfo` command which is against one single module, e.g `modinfo pcmci`, but in sosreport archives, all the "modinfo" output are merged into one `modinfo_ALL_MODULES ` file. See also: 
https://github.com/sosreport/sos/blob/a895bf4096f1dbd71c9dbd4defb47783f4ef9840/sos/plugins/kernel.py#L61.

Can we modify the existing parser `ModinfoEach` and combiner `Modinfo` to keep compitable with the sosreport?

To achieve the compatibility, the following steps can be done.

1.  Change the current spec of `modinfo` :
     From:
     ```python
     # __init__.py
     modinfo = RegistryPoint(multi_output=True)
     # default.py
     def lsmod_only_names(broker):
       return [line.split()[0] for line in lsmod[1:] if line.strip()]
     modinfo = foreach_execute(lsmod_only_names, "modinfo %s")
     ```
     To:
     ```python
     # __init__.py
     modinfo = RegistryPoint()
     # default.py
     def lsmod_only_names(broker):
       return ' '.join([line.split()[0] for line in lsmod[1:] if line.strip()])
     modinfo = command_with_args("modinfo %s", lsmod_only_names) <-- this will generate a single file contains the info of all the modules
     ```
       (This will **REMOVE** the `multi_output=True`)
2. Remove the existing parser `ModinfoEach` and combiner `Modinfo`
3. Re-implement a parser, like `ModinfoAllModules`, to parser the new spec.

The above update will change the existing APIs, However, it would work for both insights-archive sand sosreport-archives. And since the spec `modinfo` has used the `foreach_execute`,  it's not added to the uploader.json yet. Can we apply the above change?

Thanks.

**Comment by jsvob** [comment]
Hi @xiangce,

I think it will work, and it seems it has the same computational complexity, and I see no issues with your proposal.

Since the `ModInfo` combiner will provide the same API, and from rule developers' perspective the direct usage of the `ModInfoEach` parser makes little sense, and since `ModInfoEach` works for core collection only anyway, the API change won't be significant IMO.

Thanks for asking!

**Comment by xiangce** [comment]
Hi @jsvob,

Thanks for the response. In my original thought, I would like to remove the `ModInfo` combiner, since the new parser for `module_all_module` would provide all the APIs (the same to `ModInfo combiner). But just as you suggested, we'd better leave the `ModInfo` there to keep the best backward compatibility.

Thanks!

**Comment by jsvob** [comment]
Hi @xiangce ,

ah, so it seems to me the new proposed `ModInfo` parser would effectively provide the same information as the current `ModInfo` combiner. That makes sense, because the parser would run just once per system; I didn't realize it.

From my perspective, I see nothing wrong with your proposal and it certainly makes sense.

I'm not a core developer and I don't make decisions. I've just touched the modinfo code because of https://github.com/RedHatInsights/insights-core/issues/1793.

I respectfully delegate the backward compatibility matters and all other matters related to this issue to @bfahr . Thanks!

**Comment by bfahr** [comment]
@xiangce we really need to maintain backward compatibility unless there's a good reason to break it. I would be nice to have a single parser for both sosreport and insights. I would prefer to maintain the existing parser/combiner interface, but I'd also like to get @csams to weigh in on this.

**Comment by xiangce** [comment]
@bfahr - I agree with you that we should not break backward compatibility. I will add a new spec and a parser for the `modinfo_all_modules` spec, and use the existing `ModInfo` Combiner to combine them. This won't break any backward compatibility.

Thanks.
