### ISSUE TITLE
KpatchPatches Documentation and Archive Spec

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#2378]
The parser added in PR #2341 needs some additional documentation to comply with the project [documentation guidelines](https://insights-core.readthedocs.io/en/latest/docs_guidelines.html). It is also missing an archive spec for the collected data in `insights/specs/insights_archive.py`.

**Comment by xiangce** [comment]
@bfahr - Sorry for missing that when reviewing the PR. Since this [kpatch_patch_files](https://github.com/RedHatInsights/insights-core/blob/c82e08e1159337e75a6437178824cf88a5c679e8/insights/specs/default.py#L500) spec used a "@datasource", which is not able to be collected by the current client tool, it's not possible to add it to the `uploader.json` maintained by the insights-core-assets. But I agree with you that it's necessary to add the related `simple_file` to the `insights/specs/insights_archive.py`. Sorry again.
