### ISSUE TITLE
Sap HDB version parser cannot handle multiple inputs

### ISSUE THREAD

**Issue by bfahr** [RedHatInsights/insights-core#2812]
The current spec sap_hdb_version is multi_output, but the implementation in the JSON concatenates all output in one file.  The HDBVersion parser expects one set of command output per file so it will not work correctly if there is more than one SAP SID.  The parser does work correctly for core collection which does the right thing regarding command output.

**Comment by bfahr** [comment]
@xiangce @SteveHNH FYI.

**Comment by xiangce** [comment]
@bfahr, Since the "HDB version" command works for its own SAP HANA instance only, it's incorrect to let the HDBVersion parser parse all the output if there are multiple SAP HANA instances (it's rare, but I'm not sure if it's possible) running.

In other words, I don't think it's correct theoretically to use the "insights-cat" to collect this spec, since it impossible for the rule to check which HDBVersion stands for which SAP HANA, which is done via checking the "file_path"

HTH,
