### ISSUE TITLE
The class `Directory` from `ls_parser` hits exception for specical directory name

### ISSUE THREAD

**Issue by wushiqinlou** [RedHatInsights/insights-core#3858]
From some archives, the spec `ls_systemd_units` contains the following content:

~~~
/run/systemd/ask-password:********
total 0
drwxr-xr-x.  2 0 0  40 Apr 17 08:15 .
drwxr-xr-x. 17 0 0 420 Jul 21 06:44 ..

/run/systemd/ask-password********:
total 0
drwx------.  2 0 0 100 Jun 14 09:15 .
drwxr-xr-x. 17 0 0 420 Jul 21 06:44 ..
prw-------.  1 0 0   0 Jun 13 08:03 136:0
prw-------.  1 0 0   0 Jun  9 02:14 136:1
prw-------.  1 0 0   0 Jun 14 09:15 4:1
~~~

This content can hit exception `List index out of range` after this update: https://github.com/RedHatInsights/insights-core/pull/3833

~~~
 if parts[1][0].isdigit(): 
~~~

**Comment by xiangce** [comment]
The root cause of this issue should be the `Redaction` of the current insights-core, but not the #3833.

See the following code slides

https://github.com/RedHatInsights/insights-core/blob/16a2b60f38823c9d13eee8292aecf866117e88a0/insights/client/data_collector.py#L50

https://github.com/RedHatInsights/insights-core/blob/16a2b60f38823c9d13eee8292aecf866117e88a0/insights/client/constants.py#L52

You can check the "cat /etc/insights-client/.exp.sed" file in your local, it looks like:
```
❯ cat /etc/insights-client/.exp.sed
s/(password[a-zA-Z0-9_]*)(\s*\:\s*\"*\s*|\s*\"*\s*=\s*\"\s*|\s*=+\s*|\s*--md5+\s*|\s*)([a-zA-Z0-9_!@#$%^&*()+=/-]*)/\1\2********/
s/(password[a-zA-Z0-9_]*)(\s*\*+\s+)(.+)/\1\2********/
```


So, for any line in the files of the archive, if it contains a string that looks like "password:XXXXX", it will be replaced with "password:*********"

And this "redaction" is a Must-Be-Done operation per the customer configuration, unless we change the logic of the `.exp.sed`
Here is its new obfuscation/redaction implementation:
- https://github.com/RedHatInsights/insights-core/pull/3679/files#diff-74f6017461df7edf118fb17692799ead73cfa734c8063965c59d20c5c79b361aR36-R40

**Comment by xiangce** [comment]
Instead of skipping these lines (in fact, this is incorrect for the parser result), how about skipping the redaction of this spec temporarily? e.g. add it to the spec following list:

https://github.com/RedHatInsights/insights-core/blob/9d7bc9a4bb2868098b631857ccea20fa45c09349/insights/client/data_collector.py#L458-L461

```
nsights_commands/ls_-lanRL_.etc.systemd_.run.systemd_.usr.lib.systemd_.usr.local.lib.systemd_.usr.local.share.systemd_.usr.share.systemd
```
