### ISSUE TITLE
satellite_version combiner should not return None

### ISSUE THREAD

**Issue by csams** [RedHatInsights/insights-core#658]
The combiner `insights.combiners.satellite_version` has several conditions under which it might return None. Combiners whose conditions are met should either return a usable value or raise an exception.

**Comment by xiangce** [comment]
I will fix it ASAP.

**Comment by PaulWay** [comment]
Hi @csams - this has come back because I noticed that the rules were getting the Exception being raised by the `satellite_version` parser, and wanted to eliminate this.  I raised #751 to deal with this but @xiangce  has pointed out this issue which I had forgotten.

So my questions are:

* Why is returning None bad?
* What Exception should a combiner raise if it has determined that it is invalid - e.g. in this case, that Satellite is not installed and therefore has no valid version number?  Maybe we should just raise a ParseException here?
* I don't see anything in http://insights-core.readthedocs.io/en/latest/exception_model.html about this, and http://insights-core.readthedocs.io/en/latest/combiner_tutorial.html is blank; is there some documentation about what combiners should and should not return?

**Comment by PaulWay** [comment]
Hi @csams - @xiangce has filled me in on some of the discussion.  So let's change my questions to:

* I'm assuming we should raise a SkipException if it can't end up in a valid state and wants to be skipped.  Is that correct?
* Can I suggest that the documentation of SkipException be modified to include this kind of use case?  See http://insights-core.readthedocs.io/en/latest/api_index.html#insights.parsers.SkipException and http://insights-core.readthedocs.io/en/latest/exception_model.html#case-3b-parsing-data-to-find-errors-dirty-parser

**Comment by PaulWay** [comment]
Hi @csams 

Just a further note - I've tried raising a SkipException (see #751) and the SkipException gets caught in the rule tests.  I can forward you more information about this but I thought the SkipException was going to be absorbed by the parsing system.  Is this feature present in version 1.x?

Thanks in advance,

Paul

**Comment by csams** [comment]
Hey @PaulWay, `SkipComponent` and all of its subclasses (`SkipException` for now for backward compatibility) should be ignored by the core in 1.x and 3.x. #755 included the changes for 1.x and was recently merged. I'll update the docs to reflect the use case.

**Comment by csams** [comment]
Fixes in #755 #751. Combiner in master and 1.x branches are updated.
