### ISSUE TITLE
Update --force-reregister messaging

### ISSUE THREAD

**Issue by SteveHNH** [RedHatInsights/insights-core#703]
After unregistering a machine, using a standard insights run will always throw a message saying to use --force-reregister. That flag doesn't have to be used if the box is unregistered in the proper fashion. A user can just use --register again as normal.
Need to fix that so it just puts out the normal message for an unregistered machine trying to upload.

_imported from Trello_

**Comment by kylape** [comment]
@SteveHNH @gravitypriest @brantleyr @jhjaggars Can we talk about the value of `--force-reregister`?  AFAICT the only thing that makes it truly unique from `--register` is that it deletes the machine ID and regenerates a new one.  Is that something that we would want a customer to ever do?

**Comment by brantleyr** [comment]
🙅‍♂️

On Jan 15, 2018 5:26 PM, "Kyle Lape" <notifications@github.com> wrote:

@SteveHNH <https://github.com/stevehnh> @gravitypriest
<https://github.com/gravitypriest> @brantleyr <https://github.com/brantleyr>
@jhjaggars <https://github.com/jhjaggars> Can we talk about the value of
--force-reregister? AFAICT the only thing that makes it truly unique from
--register is that it deletes the machine ID and regenerates a new one. Is
that something that we would want a customer to ever do?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/RedHatInsights/insights-core/issues/703#issuecomment-357803005>,
or mute the thread

**Comment by gravitypriest** [comment]
I never saw the point of `--force-reregister` myself, and would be fine dumping it. Now to find out it's some satellite requirement or something...

**Comment by kylape** [comment]
Yep, @lphiri said it's used when cloning VMs that were already registered to Insights.  So this issue can be resolved by doing the original suggestion of changing the message when an unregistered machine tries to upload.
