### ISSUE TITLE
Command parsers to be based on a CommandParser class

### ISSUE THREAD

**Issue by PaulWay** [RedHatInsights/insights-core#898]
Command output has some common properties:
* The message '/bin/program: command or file not found' can appear in sosreports and other (earlier) outputs.  This should have one common way of being handled.
* Program outputs normally don't have blank lines at the start or end, so these should be trimmed before parsing.

It'd be good to have a common parser for commands, so I'm proposing to make a CommandParser common class that handles these things.  It would raise a ParseException if it encountered a 'command or file not found' or similar message, would strip leading and trailing blank lines of content before calling parse_content, and could provide other features for all command parsers.

**Comment by csams** [comment]
I've put additional error detection into the classes underlying datasources. 3.x command datasources have always raised exceptions if commands return non-zero or can't be found. I've changed the text based datasources to look at the first line and do the same for common error strings so we have uniform behavior for command output in old-style archives.

The common trimming functions are better as utilities, e.g. get_active_lines, rather than tied in automatically with inheritance. It's less surprising when you have to opt in than opt out. I removed some common rstrips from datasources earlier for the same reason.

We're no longer pushing the 1.x branch forward, so there's no need to update it.
